---
- name: install a list of packages
  apt:
    update_cache: yes
    cache_valid_time: 7200
    pkg:
      - iftop
      - psmisc
      - pwgen
      - vim
      - aptitude
      - fbi
      - screen
      - imagemagick
      - rpd-plym-splash
    state: latest

- name: remove unwanted packages
  apt:
    pkg:
      - cups
      - hplip
      - printer-driver-hpcups
      - pi-printer-support
    state: absent

- name: enable printing of network parameters on login
  become: false
  lineinfile:
   line: ip -o a
   path: /home/pi/.bashrc

- name: set default editor
  shell: update-alternatives --set editor /usr/bin/vim.basic

- name: enable boot splash screen
  shell: "raspi-config nonint do_boot_splash 0"
  ignore_errors: true

- name: copy welcome screen to /tmp
  copy:
    src: "{{ playbook_dir }}/welcome.jpg"
    dest: /tmp/splash.jpg
    mode: 0444

- name: setup this file as splash screen
  shell: convert -quality 85 -resize "1024x768>" /tmp/splash.jpg /usr/share/plymouth/themes/pix/splash.png

- name: ensure /home/pi/bin exists
  file:
    path: /home/pi/bin
    state: directory
    mode: 0755
  become: false